/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Algoritmo1.GUI;

import Algoritmo1.WareHouse;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.TimeUnit;

/**
 *
 * @author Jefferson Linares
 */
public class Menu extends javax.swing.JPanel {

    /**
     * Creates new form Menu
     */
    ExecutorService ejecutor;
    Window window;
    Dashboard dash;
    public Menu(ExecutorService ejecutor, Window windows, Dashboard dash) {
        initComponents();
        this.ejecutor = ejecutor;
        this.window = windows;
        this.dash = dash;
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        label_free_boxes = new javax.swing.JLabel();
        providers_in_queue = new javax.swing.JLabel();
        clients_in_queue = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 153, 255));
        setMaximumSize(new java.awt.Dimension(1000, 50));
        setPreferredSize(new java.awt.Dimension(1000, 50));

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        label_free_boxes.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        label_free_boxes.setForeground(new java.awt.Color(0, 204, 51));
        label_free_boxes.setText("Casillas Libres:");

        providers_in_queue.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        providers_in_queue.setForeground(new java.awt.Color(0, 0, 255));
        providers_in_queue.setText("Proveedores Pendientes: ");

        clients_in_queue.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        clients_in_queue.setForeground(new java.awt.Color(255, 51, 204));
        clients_in_queue.setText("Clientes Pendientes:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(label_free_boxes, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(clients_in_queue, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(providers_in_queue, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_free_boxes)
                    .addComponent(clients_in_queue)
                    .addComponent(providers_in_queue))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    
    public void ThreadAction(int option){
            try {
            for (int i = 0; i < WareHouse.threads.size(); i++) {
                Thread t = WareHouse.threads.get(i);
                if(option == 0){
                    //detener
                    this.dash.finaliceSimulation();
                    t.stop();
                }
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        try {
            ThreadAction(0);
            this.window.setVisible(false);
            //this.ejecutor.shutdown();
            //this.ejecutor.awaitTermination(Long.MAX_VALUE, TimeUnit.NANOSECONDS);
        } catch (Exception e) {
        }
        System.out.println("Salir");
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel clients_in_queue;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel label_free_boxes;
    public static javax.swing.JLabel providers_in_queue;
    // End of variables declaration//GEN-END:variables
}
